version: '3.5'
services:
    web:
        image: ${SERVER_HOST}/web:latest
        container_name: web
        env_file:
            - .env
        depends_on:
            - api
        ports:
            - ${WEB_PORT}:${WEB_PORT}
    api:
        image: ${SERVER_HOST}/api:latest
        container_name: api
        env_file:
            - .env
        volumes:
            - ./api/audios:/api/audios:rw
            - ./api/logs:/api/logs:rw
            - ./api/logs_old:/api/logs_old:rw
        ports:
            - ${API_PORT}:${API_PORT}
        networks:
            - database
networks:
    database:
        name: database
        external: true
