version: '3.9'
services:
    web:
        build:
            context: ./web
            dockerfile: ./Dockerfile.dev
        image: web:dev
        container_name: web
        tty: true # debug
        depends_on:
            - api
        ports:
            - ${WEB_PORT}:${WEB_PORT}
        volumes:
            - ./web/next:/web:rw # debug
    api:
        build:
            context: ./api
            dockerfile: ./Dockerfile.dev
        image: api:dev
        container_name: api
        tty: true # debug
        cpus: 0.7
        environment:
            NODE_ENV: ${NODE_ENV}
            MYSQL_HOST: ${MYSQL_HOST}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_TCP_PORT: ${MYSQL_TCP_PORT}
        volumes:
            - ./api/node:/api:rw # debug
        depends_on:
            - db
        ports:
            - ${API_PORT}:${API_PORT}
    db:
        image: mysql:lts
        container_name: db
        environment:
            TZ: Asia/Tokyo
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_TCP_PORT: ${MYSQL_TCP_PORT}
        volumes:
            - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
            - ./db/conf.d:/etc/mysql/conf.d
        ports:
            - ${MYSQL_TCP_PORT}:${MYSQL_TCP_PORT}
