version: '3.9'
services:
    web:
        build: ./web
        image: ${SERVER_HOST}/web:latest
        container_name: web
        environment:
            - NODE_ENV=production
        depends_on:
            - api
        ports:
            - ${WEB_PORT}:${WEB_PORT}
    api:
        build: ./api
        image: ${SERVER_HOST}/api:latest
        environment:
            - NODE_ENV=production
            - MYSQL_HOST=${MYSQL_HOST}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_TCP_PORT=${MYSQL_TCP_PORT}
        container_name: api
        cpus: 0.7
        volumes:
            - ./api/audios:/api/audios:rw
            - ./api/logs:/api/logs:rw
            - ./api/logs_old:/api/logs_old:rw
        ports:
            - ${API_PORT}:${API_PORT}
        networks:
            - database

networks:
    database:
        name: database
        external: true
