version: '3.3'
services:
    web:
        image: ${SERVER_HOST}/web:latest
        container_name: web
        restart: always
        depends_on:
            - api
        ports:
            - ${WEB_PORT}:${WEB_PORT}
    api:
        image: ${SERVER_HOST}/api:latest
        container_name: api
        restart: always
        volumes:
            - ./api/audios:/api/audios:rw
            - ./api/logs:/api/logs:rw
            - ./api/logs_ald:/api/logs_ald:rw
        ports:
            - ${API_PORT}:${API_PORT}
        networks:
            - database
networks:
    database:
        name: database
        external: true
