version: '3.8'
services:
    web:
        build: ./web
        image: ${SERVER_HOST}/web:latest
        container_name: web
        depends_on:
            - api
        ports:
            - ${WEB_PORT}:${WEB_PORT}
    api:
        build: ./api
        image: ${SERVER_HOST}/api:latest
        container_name: api
        cpus: 0.7
        environment:
            NODE_ENV: ${NODE_ENV}
            MYSQL_HOST: ${MYSQL_HOST}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_TCP_PORT: ${MYSQL_TCP_PORT}
        volumes:
            - ./api/audios:/api/audios:rw
            - ./api/logs:/api/logs:rw
            - ./api/logs_ald:/api/logs_ald:rw
        depends_on:
            - db
        ports:
            - ${API_PORT}:${API_PORT}
    db:
        build: ./db
        image: ${SERVER_HOST}/db:latest
        container_name: db
        environment:
            NODE_ENV: ${NODE_ENV}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_TCP_PORT: ${MYSQL_TCP_PORT}
        volumes:
            - ./db/sql:/var/lib/mysql
            - ./db/log:/var/log/mysql
        ports:
            - ${MYSQL_TCP_PORT}:${MYSQL_TCP_PORT}
