version: '3.3'
services:
    web:
        image: ${SERVER_HOST}/web:latest
        container_name: web
        depends_on:
            - api
        ports:
            - ${WEB_PORT}:${WEB_PORT}
    api:
        image: ${SERVER_HOST}/api:latest
        container_name: api
        volumes:
            - ./api/audios:/api/audios:rw
            - ./api/logs:/api/logs:rw
            - ./api/logs_ald:/api/logs_ald:rw
        depends_on:
            - db
        ports:
            - ${API_PORT}:${API_PORT}
    db:
        image: ${SERVER_HOST}/db:latest
        container_name: db
        volumes:
            - ./db/sql:/var/lib/mysql
            - ./db/log:/var/log/mysql
        ports:
            - ${MYSQL_TCP_PORT}:${MYSQL_TCP_PORT}
