name: docker-compose CI

on:
    workflow_dispatch:
    pull_request:
        branches: [main]
        types: [closed, synchronize]

jobs:
    build_push:
        runs-on: ubuntu-latest
        env:
            SERVER_HOST: ${{ secrets.SERVER_HOST }}
            WEB_PORT: ${{ secrets.WEB_PORT }}
            API_PORT: ${{ secrets.API_PORT }}
            MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
            MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
            MYSQL_USER: ${{ secrets.MYSQL_USER }}
            MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
            MYSQL_TCP_PORT: ${{ secrets.MYSQL_TCP_PORT }}
        steps:
            - uses: actions/checkout@v4

            - name: Docker Login
              # You may pin to the exact commit or the version.
              # uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
                  logout: false

            - name: Docker Setup Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and push Docker image api
              uses: docker/build-push-action@v6
              with:
                  context: api
                  push: true
                  tags: ghcr.io/${{ github.actor }}/api:latest
                  cache-from: type=gha
                  cache-to: type=gha,mode=max

            - name: Build and push Docker image web
              uses: docker/build-push-action@v6
              with:
                  context: web
                  push: true
                  tags: ghcr.io/${{ github.actor }}/web:latest
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
