name: docker-compose CD

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ docker-compose CI ]
    types: [ completed ] 

jobs:
  ssh_pull:
    runs-on: ubuntu-latest
    steps:
        - name: SSH Conect
          uses: LuisEnMarroquin/setup-ssh-action@v2.0.0
          with:
            # SSH origin
            ORIGIN: ${{ secrets.SERVER_HOST }}
            # SSH key
            SSHKEY: ${{ secrets.SSH_KEY }}
            # SSH host
            NAME: server
            # SSH port
            PORT: ${{ secrets.SSH_PORT }}
            # SSH user
            USER: ${{ secrets.SSH_USER }}
        
        - name: Image Pull
          run: |
            ssh server ls --help
