name: docker-compose CI

on:
    workflow_dispatch:
    pull_request:
        branches: [main]
        types: [closed, synchronize]

jobs:
    build_push:
        runs-on: ubuntu-latest
        env:
            SERVER_HOST: ${{ secrets.SERVER_HOST }}
            WEB_PORT: ${{ secrets.WEB_PORT }}
            API_PORT: ${{ secrets.API_PORT }}
        steps:
            - uses: actions/checkout@v4

            - name: Create .env file
              run: |
                  echo "NODE_ENV=production" >> .env
                  echo "SERVER_HOST=${{ secrets.SERVER_HOST }}" >> .env
                  echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env
                  echo "MYSQL_ROOT_HOST=${{ secrets.MYSQL_ROOT_HOST }}" >> .env
                  echo "MYSQL_HOST=${{ secrets.MYSQL_HOST }}" >> .env
                  echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> .env
                  echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> .env
                  echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env
                  echo "MYSQL_TCP_PORT=${{ secrets.MYSQL_TCP_PORT }}" >> .env
                  echo "WEB_PORT=${{ secrets.WEB_PORT }}" >> .env
                  echo "API_PORT=${{ secrets.API_PORT }}" >> .env

            - name: Upload .env file
              uses: actions/upload-artifact@v4
              with:
                  path: ./.env
                  name: env
                  
            - name: Check File
              run: |
                  ls -al
                  cat .env
                  
            - name: Compose build
              shell: bash
              run: |
                 dokcer-compose build

            - name: Compose push
              shell: bash
              run: |
                 dokcer-compose push

    test:
        runs-on: ubuntu-latest
        env:
            SERVER_HOST: ${{ secrets.SERVER_HOST }}
            WEB_PORT: ${{ secrets.WEB_PORT }}
            API_PORT: ${{ secrets.API_PORT }}
        
        needs: [build_push]
        steps:       
            - uses: actions/checkout@v4

            - name: Download env artifact
              uses: actions/download-artifact@v4
              with:
                  name: env
                  path: ./
            
            - name: test docker-compose
              shell: bash
              run: |
                  docker network create database
                  docker-compose -f docker-compose.server.yml up -d
                  docker-compose -f docker-compose.server.yml ps
                  docker-compose -f docker-compose.server.yml logs
                  docker-compose -f docker-compose.server.yml down

