name: docker-compose CD

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ docker-compose CI ]
    types: [ completed ] 

jobs:
  ssh_pull:
    runs-on: ubuntu-latest
    steps:
        - name: Make fail if the previous workflow was failed
          if: ${{ github.event.workflow_run.conclusion != 'success' }}
          run: |
            echo '::error::Previous workflow was failed'
            exit 1
            
        - name: SSH Conect
          uses: appleboy/ssh-action@v1.0.3
          with:
            key:  ${{ secrets.SSH_KEY }}
            passphrase: ${{ secrets.SSH_KEY_PASS }}
            host: ${{ secrets.SERVER_HOST }}
            username: ${{ secrets.SSH_USER }}
            port: ${{ secrets.SSH_PORT }}
            script: |
              cd ${{ secrets.TARGET_DIR }}
              sudo docker-compose down --rmi all --volumes --remove-orphans
              sudo docker-compose --env-file=./.env up -d
