name: docker-compose CD

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ docker-compose CI ]
    types: [ completed ] 

jobs:
  ssh_pull:
    runs-on: ubuntu-latest
    steps:
        - name: SSH Conect
          uses: appleboy/ssh-action@v1.0.3
          with:
            key:  ${{ secrets.SSH_KEY }}
            host: ${{ secrets.SERVER_HOST }}
            username: ${{ secrets.SSH_USER }}
            port: ${{ secrets.SSH_PORT }}
            script: |
              ls --help
