name: docker-compose CI

on:
  workflow_dispatch:
  pull_request:
      branches: [ main ] 
      types : [ closed , synchronize]

jobs:
  build_push:
    runs-on: ubuntu-latest
    env:
        NODE_ENV: production
        SERVER_HOST: ${{ secrets.SERVER_HOST }}
        MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
        MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        MYSQL_USER: ${{ secrets.MYSQL_USER }}
        MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        MYSQL_TCP_PORT: ${{ secrets.MYSQL_TCP_PORT }}
        WEB_PORT: ${{ secrets.WEB_PORT }}
        API_PORT: ${{ secrets.API_PORT }}
    steps:
      - uses: actions/checkout@v4

      - name: compose build
        shell: bash
        run: |
          docker-compose -f docker-compose.yml build

      - name: compose push
        shell: bash
        run: |
          docker-compose -f docker-compose.yml push
